var products = [
    {
      id: 1,
      title: "phone",
      description: "An apple mobile which is nothing like apple",
      price: 700,
      discountPercentage: 12.96,
      rating: 4.69,
      stock: 10,
      brand: "Apple",
      category: "smartphones",
      img: "https://th.bing.com/th/id/OIP.pFkxZ-80qxSzCa1yIz8mEQHaEd?pid=ImgDet&rs=1",
    },
    {
      id: 2,
      title: "Labtop",
      description:
        "MacBook Pro، Apple، Laptop...",
      price: 1500,
      discountPercentage: 17.94,
      rating: 4.44,
      stock: 1,
      brand: "MacBook",
      category: "smartcomputer",
      img: "https://th.bing.com/th/id/OIP.GrOte4yeTotRnN6-42S1SwHaGZ?pid=ImgDet&rs=1",
    },
    {
      id: 3,
      title: "Smart Watch",
      description:
        "Huawei Smart watch...",
      price: 200,
      discountPercentage: 15.46,
      rating: 4.09,
      stock: 0,
      brand: "Huawei",
      category: "smartwatch",
      img: "https://cf5.s3.souqcdn.com/item/2019/10/08/73/36/22/03/item_L_73362203_f0ee58beac895.jpg",
    },
    {
      id: 4,
      title: "BlackBerry",
      description: "4G BlackBerry Phone...",
      price: 850,
      discountPercentage: 17.91,
      rating: 4.3,
      stock: 2,
      brand: "BlackBerry",
      category: "smartphones",
      img: "https://th.bing.com/th/id/OIP.kLlwFbHIs6FwBPXgTzJhHQHaEh?pid=ImgDet&rs=1",
    },
    {
      id: 5,
      title: "Huawei P30",
      description:
        "Huawei’s  yesterday its way to the UK.",
      price: 499,
      discountPercentage: 10.58,
      rating: 4.09,
      stock: 15,
      brand: "Huawei",
      category: "smartphones",
      img: "https://dummyjson.com/image/i/products/5/thumbnail.jpg",
    },
    {
      id: 6,
      title: "PlayStation",
      description:
        "Game Device Play Station",
      price: 1749,
      discountPercentage: 11.02,
      rating: 4.57,
      stock: 7,
      brand: "Sony",
      category: "Gaming Device",
      img: "https://t-rendy.com/wp-content/uploads/2020/06/ss5-1024x577.jpg",
    },
  ];